<?php

use Illuminate\Database\Seeder;

class BookingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bookings')->delete();
        
        \DB::table('bookings')->insert(array (
            0 => 
            array (
                'bookingId' => 1,
                'petId' => 84,
                'staffId' => 5,
                'bookingDateTime' => '2012-09-29 13:30:00',
                'symptoms' => 'hair loss',
                'treatments' => 'give a "good boy"',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'bookingId' => 2,
                'petId' => 84,
                'staffId' => 2,
                'bookingDateTime' => '2011-03-26 15:45:00',
                'symptoms' => 'excessive tiredness',
                'treatments' => 'meditation',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'bookingId' => 3,
                'petId' => 97,
                'staffId' => 5,
                'bookingDateTime' => '2011-04-03 12:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'bookingId' => 4,
                'petId' => 34,
                'staffId' => 5,
                'bookingDateTime' => '2011-05-09 12:00:00',
                'symptoms' => 'fleas',
                'treatments' => 'drugs',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'bookingId' => 5,
                'petId' => 49,
                'staffId' => 5,
                'bookingDateTime' => '2012-10-11 15:00:00',
                'symptoms' => 'excessive thirstiness',
                'treatments' => 'hydrotherapy',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'bookingId' => 6,
                'petId' => 80,
                'staffId' => 2,
                'bookingDateTime' => '2011-04-22 14:45:00',
                'symptoms' => 'uncontrollable peeing',
                'treatments' => 'hydrotherapy',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'bookingId' => 7,
                'petId' => 61,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-10 12:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'bookingId' => 8,
                'petId' => 75,
                'staffId' => 2,
                'bookingDateTime' => '2012-07-03 10:15:00',
                'symptoms' => 'limping',
                'treatments' => 'meditation',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'bookingId' => 9,
                'petId' => 88,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-13 16:00:00',
                'symptoms' => 'diarrhoea',
                'treatments' => 'give a "good boy"',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'bookingId' => 10,
                'petId' => 21,
                'staffId' => 3,
                'bookingDateTime' => '2011-04-21 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'bookingId' => 11,
                'petId' => 54,
                'staffId' => 3,
                'bookingDateTime' => '2011-11-28 13:30:00',
                'symptoms' => 'vomiting',
                'treatments' => 'acupuncture',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'bookingId' => 12,
                'petId' => 89,
                'staffId' => 3,
                'bookingDateTime' => '2011-12-16 11:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'bookingId' => 13,
                'petId' => 82,
                'staffId' => 2,
                'bookingDateTime' => '2011-06-05 12:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'bookingId' => 14,
                'petId' => 48,
                'staffId' => 3,
                'bookingDateTime' => '2012-10-24 09:30:00',
                'symptoms' => 'poor eyesight, inappropriate defecation',
                'treatments' => 'bandage application',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'bookingId' => 15,
                'petId' => 81,
                'staffId' => 3,
                'bookingDateTime' => '2012-02-03 12:30:00',
                'symptoms' => 'deafness',
                'treatments' => 'hypnotherapy',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'bookingId' => 16,
                'petId' => 51,
                'staffId' => 5,
                'bookingDateTime' => '2012-08-26 13:00:00',
                'symptoms' => 'poor eyesight',
                'treatments' => 'medicinal bath',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'bookingId' => 17,
                'petId' => 95,
                'staffId' => 3,
                'bookingDateTime' => '2011-05-09 12:15:00',
                'symptoms' => 'limping',
                'treatments' => 'tooth clean',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'bookingId' => 18,
                'petId' => 56,
                'staffId' => 5,
                'bookingDateTime' => '2012-03-14 09:15:00',
                'symptoms' => 'excessive tiredness',
                'treatments' => 'electric shock therapy',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'bookingId' => 19,
                'petId' => 85,
                'staffId' => 3,
                'bookingDateTime' => '2012-03-18 16:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'bookingId' => 20,
                'petId' => 57,
                'staffId' => 3,
                'bookingDateTime' => '2012-07-14 13:00:00',
                'symptoms' => 'anxiety',
                'treatments' => 'non-invasive surgery',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'bookingId' => 21,
                'petId' => 25,
                'staffId' => 2,
                'bookingDateTime' => '2011-01-13 11:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'bookingId' => 22,
                'petId' => 85,
                'staffId' => 5,
                'bookingDateTime' => '2012-05-15 15:45:00',
                'symptoms' => 'constipation, deafness',
                'treatments' => 'tooth clean',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'bookingId' => 23,
                'petId' => 72,
                'staffId' => 3,
                'bookingDateTime' => '2011-10-15 11:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'bookingId' => 24,
                'petId' => 95,
                'staffId' => 5,
                'bookingDateTime' => '2012-04-21 16:30:00',
                'symptoms' => 'bottom scraping, deafness',
                'treatments' => 'massage',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'bookingId' => 25,
                'petId' => 28,
                'staffId' => 5,
                'bookingDateTime' => '2012-05-13 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'bookingId' => 26,
                'petId' => 49,
                'staffId' => 2,
                'bookingDateTime' => '2011-08-18 09:30:00',
                'symptoms' => 'hair loss',
                'treatments' => 'a good corking',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'bookingId' => 27,
                'petId' => 102,
                'staffId' => 5,
                'bookingDateTime' => '2012-04-30 17:00:00',
                'symptoms' => 'other parasites',
                'treatments' => 'suture',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'bookingId' => 28,
                'petId' => 110,
                'staffId' => 2,
                'bookingDateTime' => '2012-12-11 14:00:00',
                'symptoms' => 'other parasites',
                'treatments' => 'electric shock therapy',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'bookingId' => 29,
                'petId' => 9,
                'staffId' => 3,
                'bookingDateTime' => '2011-06-15 12:30:00',
                'symptoms' => 'wheezing',
                'treatments' => 'stitches',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'bookingId' => 30,
                'petId' => 70,
                'staffId' => 3,
                'bookingDateTime' => '2012-06-17 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'bookingId' => 31,
                'petId' => 98,
                'staffId' => 5,
                'bookingDateTime' => '2012-10-29 09:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'bookingId' => 32,
                'petId' => 58,
                'staffId' => 5,
                'bookingDateTime' => '2011-11-27 09:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'bookingId' => 33,
                'petId' => 92,
                'staffId' => 5,
                'bookingDateTime' => '2011-02-18 12:00:00',
                'symptoms' => 'obesity',
                'treatments' => 'hydrotherapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'bookingId' => 34,
                'petId' => 26,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-02 13:30:00',
                'symptoms' => 'poor eyesight, joint stiffness',
                'treatments' => 'wallet massage',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'bookingId' => 35,
                'petId' => 86,
                'staffId' => 2,
                'bookingDateTime' => '2011-12-24 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'bookingId' => 36,
                'petId' => 92,
                'staffId' => 5,
                'bookingDateTime' => '2012-12-26 14:45:00',
                'symptoms' => 'sneezing',
                'treatments' => 'tooth clean',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'bookingId' => 37,
                'petId' => 73,
                'staffId' => 3,
                'bookingDateTime' => '2012-04-19 09:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'bookingId' => 38,
                'petId' => 85,
                'staffId' => 5,
                'bookingDateTime' => '2011-12-08 14:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'bookingId' => 39,
                'petId' => 106,
                'staffId' => 5,
                'bookingDateTime' => '2011-03-27 17:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'bookingId' => 40,
                'petId' => 107,
                'staffId' => 5,
                'bookingDateTime' => '2012-10-23 10:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'bookingId' => 41,
                'petId' => 88,
                'staffId' => 3,
                'bookingDateTime' => '2013-01-21 14:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'bookingId' => 42,
                'petId' => 77,
                'staffId' => 2,
                'bookingDateTime' => '2012-04-23 10:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'bookingId' => 43,
                'petId' => 105,
                'staffId' => 5,
                'bookingDateTime' => '2012-08-11 09:00:00',
                'symptoms' => 'sneezing',
                'treatments' => 'meditation',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'bookingId' => 44,
                'petId' => 98,
                'staffId' => 3,
                'bookingDateTime' => '2011-06-19 11:15:00',
                'symptoms' => 'vomiting',
                'treatments' => 'give a "good boy"',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'bookingId' => 45,
                'petId' => 106,
                'staffId' => 5,
                'bookingDateTime' => '2012-07-23 13:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'bookingId' => 46,
                'petId' => 51,
                'staffId' => 3,
                'bookingDateTime' => '2011-06-07 11:15:00',
                'symptoms' => 'poor eyesight',
                'treatments' => 'hypnotherapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'bookingId' => 47,
                'petId' => 106,
                'staffId' => 3,
                'bookingDateTime' => '2011-11-06 10:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'bookingId' => 48,
                'petId' => 52,
                'staffId' => 3,
                'bookingDateTime' => '2011-12-24 14:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'bookingId' => 49,
                'petId' => 101,
                'staffId' => 2,
                'bookingDateTime' => '2011-09-21 15:45:00',
                'symptoms' => 'poor eyesight, other parasites',
                'treatments' => 'invasive surgery',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'bookingId' => 50,
                'petId' => 41,
                'staffId' => 2,
                'bookingDateTime' => '2012-07-01 13:00:00',
                'symptoms' => 'obesity, constipation, fleas',
                'treatments' => 'medicinal bath',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'bookingId' => 51,
                'petId' => 60,
                'staffId' => 2,
                'bookingDateTime' => '2012-09-03 16:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'bookingId' => 52,
                'petId' => 88,
                'staffId' => 3,
                'bookingDateTime' => '2011-06-30 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'bookingId' => 53,
                'petId' => 14,
                'staffId' => 3,
                'bookingDateTime' => '2012-08-25 12:45:00',
                'symptoms' => 'limping, inappropriate defecation',
                'treatments' => 'invasive surgery',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'bookingId' => 54,
                'petId' => 15,
                'staffId' => 5,
                'bookingDateTime' => '2011-11-25 14:30:00',
                'symptoms' => 'vomiting, crying',
                'treatments' => 'invasive surgery',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'bookingId' => 55,
                'petId' => 86,
                'staffId' => 5,
                'bookingDateTime' => '2012-08-01 12:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'bookingId' => 56,
                'petId' => 19,
                'staffId' => 5,
                'bookingDateTime' => '2012-01-12 10:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'bookingId' => 57,
                'petId' => 2,
                'staffId' => 2,
                'bookingDateTime' => '2011-04-02 14:15:00',
                'symptoms' => 'sore paw',
                'treatments' => 'give a "good boy"',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'bookingId' => 58,
                'petId' => 69,
                'staffId' => 2,
                'bookingDateTime' => '2011-12-18 14:45:00',
                'symptoms' => 'diarrhoea',
                'treatments' => 'emetic procedure',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'bookingId' => 59,
                'petId' => 77,
                'staffId' => 2,
                'bookingDateTime' => '2011-02-18 16:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'bookingId' => 60,
                'petId' => 23,
                'staffId' => 2,
                'bookingDateTime' => '2012-04-05 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'bookingId' => 61,
                'petId' => 53,
                'staffId' => 3,
                'bookingDateTime' => '2011-01-06 14:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'bookingId' => 62,
                'petId' => 77,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-12 11:30:00',
                'symptoms' => 'anxiety',
                'treatments' => 'tooth extraction',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'bookingId' => 63,
                'petId' => 58,
                'staffId' => 5,
                'bookingDateTime' => '2012-02-20 09:30:00',
                'symptoms' => 'excessive thirstiness, constipation',
                'treatments' => 'suture',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'bookingId' => 64,
                'petId' => 3,
                'staffId' => 3,
                'bookingDateTime' => '2012-12-30 10:45:00',
                'symptoms' => 'flatulence',
                'treatments' => 'electric shock therapy',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'bookingId' => 65,
                'petId' => 32,
                'staffId' => 2,
                'bookingDateTime' => '2012-04-09 17:00:00',
                'symptoms' => 'obesity',
                'treatments' => 'cuddles',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'bookingId' => 66,
                'petId' => 43,
                'staffId' => 2,
                'bookingDateTime' => '2012-11-30 13:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'bookingId' => 67,
                'petId' => 16,
                'staffId' => 2,
                'bookingDateTime' => '2011-09-03 12:00:00',
                'symptoms' => 'limping',
                'treatments' => 'cuddles',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'bookingId' => 68,
                'petId' => 73,
                'staffId' => 5,
                'bookingDateTime' => '2011-04-25 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'bookingId' => 69,
                'petId' => 104,
                'staffId' => 3,
                'bookingDateTime' => '2012-10-30 10:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'bookingId' => 70,
                'petId' => 72,
                'staffId' => 5,
                'bookingDateTime' => '2012-11-16 13:00:00',
                'symptoms' => 'crying',
                'treatments' => 'meditation',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'bookingId' => 71,
                'petId' => 81,
                'staffId' => 5,
                'bookingDateTime' => '2012-06-26 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'bookingId' => 72,
                'petId' => 7,
                'staffId' => 2,
                'bookingDateTime' => '2012-06-26 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'bookingId' => 73,
                'petId' => 75,
                'staffId' => 5,
                'bookingDateTime' => '2012-11-29 10:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'bookingId' => 74,
                'petId' => 68,
                'staffId' => 2,
                'bookingDateTime' => '2011-05-28 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'bookingId' => 75,
                'petId' => 78,
                'staffId' => 3,
                'bookingDateTime' => '2012-03-03 11:45:00',
                'symptoms' => 'joint stiffness',
                'treatments' => 'cuddles',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'bookingId' => 76,
                'petId' => 1,
                'staffId' => 5,
                'bookingDateTime' => '2012-10-01 11:30:00',
                'symptoms' => 'crying',
                'treatments' => 'a good corking',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'bookingId' => 77,
                'petId' => 7,
                'staffId' => 5,
                'bookingDateTime' => '2011-06-09 13:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'bookingId' => 78,
                'petId' => 13,
                'staffId' => 2,
                'bookingDateTime' => '2011-09-02 14:15:00',
                'symptoms' => 'diarrhoea, anxiety',
                'treatments' => 'give a "good boy"',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'bookingId' => 79,
                'petId' => 110,
                'staffId' => 5,
                'bookingDateTime' => '2011-08-28 16:15:00',
                'symptoms' => 'limping',
                'treatments' => 'psychotherapy',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'bookingId' => 80,
                'petId' => 60,
                'staffId' => 5,
                'bookingDateTime' => '2012-08-19 10:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'bookingId' => 81,
                'petId' => 2,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-28 09:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'bookingId' => 82,
                'petId' => 105,
                'staffId' => 3,
                'bookingDateTime' => '2011-08-25 15:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'bookingId' => 83,
                'petId' => 38,
                'staffId' => 2,
                'bookingDateTime' => '2011-01-28 14:30:00',
                'symptoms' => 'sore paw',
                'treatments' => 'saw pore',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'bookingId' => 84,
                'petId' => 58,
                'staffId' => 2,
                'bookingDateTime' => '2012-01-28 14:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'bookingId' => 85,
                'petId' => 104,
                'staffId' => 3,
                'bookingDateTime' => '2012-09-11 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'bookingId' => 86,
                'petId' => 49,
                'staffId' => 3,
                'bookingDateTime' => '2012-03-08 16:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'bookingId' => 87,
                'petId' => 41,
                'staffId' => 2,
                'bookingDateTime' => '2012-07-23 14:30:00',
                'symptoms' => 'obesity, inappropriate defecation',
                'treatments' => 'suture',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'bookingId' => 88,
                'petId' => 107,
                'staffId' => 3,
                'bookingDateTime' => '2012-01-30 14:30:00',
                'symptoms' => 'sneezing',
                'treatments' => 'massage',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'bookingId' => 89,
                'petId' => 52,
                'staffId' => 5,
                'bookingDateTime' => '2012-02-01 09:45:00',
                'symptoms' => 'hair loss, ticks',
                'treatments' => 'emetic procedure',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'bookingId' => 90,
                'petId' => 24,
                'staffId' => 2,
                'bookingDateTime' => '2011-06-25 11:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'bookingId' => 91,
                'petId' => 78,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-30 15:45:00',
                'symptoms' => 'other parasites',
                'treatments' => 'electric shock therapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'bookingId' => 92,
                'petId' => 33,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-27 11:45:00',
                'symptoms' => 'sore paw, crying',
                'treatments' => 'acupuncture',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'bookingId' => 93,
                'petId' => 55,
                'staffId' => 3,
                'bookingDateTime' => '2011-10-21 16:30:00',
                'symptoms' => 'obesity',
                'treatments' => 'massage',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'bookingId' => 94,
                'petId' => 97,
                'staffId' => 3,
                'bookingDateTime' => '2012-09-29 12:45:00',
                'symptoms' => 'anxiety',
                'treatments' => 'tooth extraction',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'bookingId' => 95,
                'petId' => 17,
                'staffId' => 2,
                'bookingDateTime' => '2012-09-09 16:00:00',
                'symptoms' => 'constipation, flatulence',
                'treatments' => 'tooth extraction',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'bookingId' => 96,
                'petId' => 14,
                'staffId' => 5,
                'bookingDateTime' => '2011-11-22 12:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'bookingId' => 97,
                'petId' => 87,
                'staffId' => 2,
                'bookingDateTime' => '2011-12-20 17:00:00',
                'symptoms' => 'limping',
                'treatments' => 'suture',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'bookingId' => 98,
                'petId' => 107,
                'staffId' => 3,
                'bookingDateTime' => '2011-03-15 12:00:00',
                'symptoms' => 'deafness',
                'treatments' => 'tooth extraction',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'bookingId' => 99,
                'petId' => 83,
                'staffId' => 5,
                'bookingDateTime' => '2011-04-30 12:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'bookingId' => 100,
                'petId' => 21,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-16 14:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'bookingId' => 101,
                'petId' => 98,
                'staffId' => 5,
                'bookingDateTime' => '2012-03-03 11:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'bookingId' => 102,
                'petId' => 52,
                'staffId' => 5,
                'bookingDateTime' => '2011-07-04 17:00:00',
                'symptoms' => 'crying',
                'treatments' => 'non-invasive surgery',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'bookingId' => 103,
                'petId' => 26,
                'staffId' => 5,
                'bookingDateTime' => '2012-05-24 16:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'bookingId' => 104,
                'petId' => 89,
                'staffId' => 3,
                'bookingDateTime' => '2013-01-16 16:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'bookingId' => 105,
                'petId' => 60,
                'staffId' => 2,
                'bookingDateTime' => '2011-11-29 12:45:00',
                'symptoms' => 'fleas',
                'treatments' => 'suture',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'bookingId' => 106,
                'petId' => 91,
                'staffId' => 2,
                'bookingDateTime' => '2011-08-21 10:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'bookingId' => 107,
                'petId' => 39,
                'staffId' => 2,
                'bookingDateTime' => '2012-10-05 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'bookingId' => 108,
                'petId' => 26,
                'staffId' => 5,
                'bookingDateTime' => '2011-04-08 12:45:00',
                'symptoms' => 'vomiting, other parasites',
                'treatments' => 'bandage application',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'bookingId' => 109,
                'petId' => 73,
                'staffId' => 3,
                'bookingDateTime' => '2011-01-16 15:15:00',
                'symptoms' => 'other parasites',
                'treatments' => 'psychotherapy',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'bookingId' => 110,
                'petId' => 30,
                'staffId' => 2,
                'bookingDateTime' => '2012-08-09 09:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'bookingId' => 111,
                'petId' => 108,
                'staffId' => 3,
                'bookingDateTime' => '2011-09-18 17:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'bookingId' => 112,
                'petId' => 105,
                'staffId' => 2,
                'bookingDateTime' => '2011-05-22 09:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'bookingId' => 113,
                'petId' => 13,
                'staffId' => 3,
                'bookingDateTime' => '2012-12-10 16:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'bookingId' => 114,
                'petId' => 29,
                'staffId' => 5,
                'bookingDateTime' => '2011-07-28 11:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'bookingId' => 115,
                'petId' => 17,
                'staffId' => 5,
                'bookingDateTime' => '2011-06-13 09:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'bookingId' => 116,
                'petId' => 23,
                'staffId' => 2,
                'bookingDateTime' => '2012-01-29 11:00:00',
                'symptoms' => 'anxiety',
                'treatments' => 'invasive surgery',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'bookingId' => 117,
                'petId' => 91,
                'staffId' => 5,
                'bookingDateTime' => '2012-06-25 13:30:00',
                'symptoms' => 'joint stiffness',
                'treatments' => 'tooth clean',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'bookingId' => 118,
                'petId' => 110,
                'staffId' => 2,
                'bookingDateTime' => '2012-02-11 13:00:00',
                'symptoms' => 'constipation',
                'treatments' => 'stitches',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'bookingId' => 119,
                'petId' => 48,
                'staffId' => 2,
                'bookingDateTime' => '2012-04-14 10:45:00',
                'symptoms' => 'hair loss',
                'treatments' => 'tooth clean',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'bookingId' => 120,
                'petId' => 28,
                'staffId' => 3,
                'bookingDateTime' => '2011-02-12 12:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'bookingId' => 121,
                'petId' => 56,
                'staffId' => 2,
                'bookingDateTime' => '2011-11-12 15:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'bookingId' => 122,
                'petId' => 65,
                'staffId' => 3,
                'bookingDateTime' => '2012-08-30 15:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'bookingId' => 123,
                'petId' => 103,
                'staffId' => 2,
                'bookingDateTime' => '2011-09-01 11:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'bookingId' => 124,
                'petId' => 65,
                'staffId' => 5,
                'bookingDateTime' => '2011-04-10 09:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'bookingId' => 125,
                'petId' => 61,
                'staffId' => 5,
                'bookingDateTime' => '2012-07-03 15:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'bookingId' => 126,
                'petId' => 62,
                'staffId' => 3,
                'bookingDateTime' => '2011-07-18 10:15:00',
                'symptoms' => 'excessive thirstiness',
                'treatments' => 'stitches',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'bookingId' => 127,
                'petId' => 36,
                'staffId' => 2,
                'bookingDateTime' => '2011-02-22 14:00:00',
                'symptoms' => 'sore paw, sneezing',
                'treatments' => 'invasive surgery',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'bookingId' => 128,
                'petId' => 41,
                'staffId' => 2,
                'bookingDateTime' => '2012-03-03 15:45:00',
                'symptoms' => 'constipation',
                'treatments' => 'electric shock therapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'bookingId' => 129,
                'petId' => 9,
                'staffId' => 3,
                'bookingDateTime' => '2013-01-24 11:15:00',
                'symptoms' => 'fleas',
                'treatments' => 'psychotherapy',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'bookingId' => 130,
                'petId' => 107,
                'staffId' => 2,
                'bookingDateTime' => '2011-02-20 11:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'bookingId' => 131,
                'petId' => 8,
                'staffId' => 2,
                'bookingDateTime' => '2011-08-04 16:45:00',
                'symptoms' => 'joint stiffness',
                'treatments' => 'non-invasive surgery',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'bookingId' => 132,
                'petId' => 3,
                'staffId' => 3,
                'bookingDateTime' => '2011-12-23 10:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'bookingId' => 133,
                'petId' => 69,
                'staffId' => 3,
                'bookingDateTime' => '2012-04-14 12:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'bookingId' => 134,
                'petId' => 94,
                'staffId' => 3,
                'bookingDateTime' => '2012-10-12 13:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'bookingId' => 135,
                'petId' => 26,
                'staffId' => 3,
                'bookingDateTime' => '2011-10-24 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'bookingId' => 136,
                'petId' => 19,
                'staffId' => 2,
                'bookingDateTime' => '2012-08-29 11:30:00',
                'symptoms' => 'joint stiffness',
                'treatments' => 'give a "good boy"',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'bookingId' => 137,
                'petId' => 39,
                'staffId' => 3,
                'bookingDateTime' => '2012-08-14 09:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'bookingId' => 138,
                'petId' => 86,
                'staffId' => 5,
                'bookingDateTime' => '2012-04-27 14:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'bookingId' => 139,
                'petId' => 53,
                'staffId' => 3,
                'bookingDateTime' => '2011-08-28 12:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'bookingId' => 140,
                'petId' => 47,
                'staffId' => 3,
                'bookingDateTime' => '2012-10-20 16:15:00',
                'symptoms' => 'excessive thirstiness',
                'treatments' => 'acupuncture',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'bookingId' => 141,
                'petId' => 47,
                'staffId' => 2,
                'bookingDateTime' => '2012-08-31 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'bookingId' => 142,
                'petId' => 67,
                'staffId' => 5,
                'bookingDateTime' => '2011-10-21 14:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'bookingId' => 143,
                'petId' => 61,
                'staffId' => 5,
                'bookingDateTime' => '2012-02-29 12:45:00',
                'symptoms' => 'inappropriate defecation',
                'treatments' => 'a good corking',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'bookingId' => 144,
                'petId' => 28,
                'staffId' => 2,
                'bookingDateTime' => '2012-03-29 11:15:00',
                'symptoms' => 'fleas',
                'treatments' => 'acupuncture',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'bookingId' => 145,
                'petId' => 2,
                'staffId' => 3,
                'bookingDateTime' => '2012-04-19 15:00:00',
                'symptoms' => 'excessive tiredness',
                'treatments' => 'hydrotherapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'bookingId' => 146,
                'petId' => 81,
                'staffId' => 2,
                'bookingDateTime' => '2011-08-31 16:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'bookingId' => 147,
                'petId' => 26,
                'staffId' => 5,
                'bookingDateTime' => '2013-01-16 11:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'bookingId' => 148,
                'petId' => 58,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-04 09:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'bookingId' => 149,
                'petId' => 69,
                'staffId' => 5,
                'bookingDateTime' => '2011-05-27 12:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'bookingId' => 150,
                'petId' => 25,
                'staffId' => 3,
                'bookingDateTime' => '2012-01-31 14:15:00',
                'symptoms' => 'anxiety, sneezing',
                'treatments' => 'wallet massage',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'bookingId' => 151,
                'petId' => 35,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-17 09:15:00',
                'symptoms' => 'other parasites',
                'treatments' => 'hydrotherapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'bookingId' => 152,
                'petId' => 67,
                'staffId' => 5,
                'bookingDateTime' => '2011-03-31 14:15:00',
                'symptoms' => 'wheezing, fleas',
                'treatments' => 'hydrotherapy',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'bookingId' => 153,
                'petId' => 94,
                'staffId' => 3,
                'bookingDateTime' => '2012-11-18 16:30:00',
                'symptoms' => 'deafness',
                'treatments' => 'a good corking',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'bookingId' => 154,
                'petId' => 10,
                'staffId' => 3,
                'bookingDateTime' => '2012-06-07 15:00:00',
                'symptoms' => 'excessive thirstiness, fleas',
                'treatments' => 'non-invasive surgery',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'bookingId' => 155,
                'petId' => 41,
                'staffId' => 5,
                'bookingDateTime' => '2013-01-29 13:15:00',
                'symptoms' => 'sneezing',
                'treatments' => 'bandage application',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'bookingId' => 156,
                'petId' => 67,
                'staffId' => 2,
                'bookingDateTime' => '2011-12-14 14:15:00',
                'symptoms' => 'bottom scraping',
                'treatments' => 'medicinal bath',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'bookingId' => 157,
                'petId' => 6,
                'staffId' => 2,
                'bookingDateTime' => '2011-10-28 10:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'bookingId' => 158,
                'petId' => 53,
                'staffId' => 5,
                'bookingDateTime' => '2012-11-17 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'bookingId' => 159,
                'petId' => 16,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-18 13:45:00',
                'symptoms' => 'anxiety',
                'treatments' => 'enema',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'bookingId' => 160,
                'petId' => 58,
                'staffId' => 3,
                'bookingDateTime' => '2013-01-08 09:30:00',
                'symptoms' => 'bottom scraping',
                'treatments' => 'meditation',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'bookingId' => 161,
                'petId' => 15,
                'staffId' => 5,
                'bookingDateTime' => '2012-11-30 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'bookingId' => 162,
                'petId' => 70,
                'staffId' => 3,
                'bookingDateTime' => '2012-04-08 15:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'bookingId' => 163,
                'petId' => 89,
                'staffId' => 5,
                'bookingDateTime' => '2012-04-26 15:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'bookingId' => 164,
                'petId' => 12,
                'staffId' => 3,
                'bookingDateTime' => '2012-12-28 13:45:00',
                'symptoms' => 'sneezing',
                'treatments' => 'cuddles',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'bookingId' => 165,
                'petId' => 10,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-23 11:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 6 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'bookingId' => 166,
                'petId' => 110,
                'staffId' => 3,
                'bookingDateTime' => '2011-09-08 13:00:00',
                'symptoms' => 'diarrhoea',
                'treatments' => 'non-invasive surgery',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'bookingId' => 167,
                'petId' => 85,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-06 09:15:00',
                'symptoms' => 'poor eyesight',
                'treatments' => 'hypnotherapy',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'bookingId' => 168,
                'petId' => 70,
                'staffId' => 2,
                'bookingDateTime' => '2012-07-23 16:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'bookingId' => 169,
                'petId' => 83,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-30 16:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'bookingId' => 170,
                'petId' => 41,
                'staffId' => 2,
                'bookingDateTime' => '2012-10-11 09:00:00',
                'symptoms' => 'sneezing',
                'treatments' => 'hydrotherapy',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'bookingId' => 171,
                'petId' => 41,
                'staffId' => 2,
                'bookingDateTime' => '2012-08-26 15:15:00',
                'symptoms' => 'diarrhoea, joint stiffness',
                'treatments' => 'electric shock therapy',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'bookingId' => 172,
                'petId' => 30,
                'staffId' => 5,
                'bookingDateTime' => '2011-03-27 15:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'bookingId' => 173,
                'petId' => 91,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-26 09:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 12 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'bookingId' => 174,
                'petId' => 66,
                'staffId' => 5,
                'bookingDateTime' => '2011-08-18 09:00:00',
                'symptoms' => 'excessive thirstiness, uncontrollable peeing, flatulence',
                'treatments' => 'massage',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'bookingId' => 175,
                'petId' => 27,
                'staffId' => 5,
                'bookingDateTime' => '2011-08-05 11:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'bookingId' => 176,
                'petId' => 96,
                'staffId' => 3,
                'bookingDateTime' => '2011-09-08 12:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'bookingId' => 177,
                'petId' => 107,
                'staffId' => 2,
                'bookingDateTime' => '2012-05-12 13:15:00',
                'symptoms' => 'deafness',
                'treatments' => 'stitches',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'bookingId' => 178,
                'petId' => 27,
                'staffId' => 2,
                'bookingDateTime' => '2011-09-25 11:30:00',
                'symptoms' => 'joint stiffness',
                'treatments' => 'stitches',
                'notes' => 'See again in 3 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'bookingId' => 179,
                'petId' => 36,
                'staffId' => 3,
                'bookingDateTime' => '2012-05-22 10:00:00',
                'symptoms' => 'limping',
                'treatments' => 'hydrotherapy',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'bookingId' => 180,
                'petId' => 9,
                'staffId' => 2,
                'bookingDateTime' => '2013-01-23 14:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'bookingId' => 181,
                'petId' => 94,
                'staffId' => 3,
                'bookingDateTime' => '2011-09-12 16:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'bookingId' => 182,
                'petId' => 67,
                'staffId' => 3,
                'bookingDateTime' => '2011-06-06 14:30:00',
                'symptoms' => 'deafness',
                'treatments' => 'hydrotherapy',
                'notes' => 'See again in 1 month',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'bookingId' => 183,
                'petId' => 91,
                'staffId' => 5,
                'bookingDateTime' => '2011-01-19 13:00:00',
                'symptoms' => 'uncontrollable peeing',
                'treatments' => 'cuddles',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'bookingId' => 184,
                'petId' => 9,
                'staffId' => 2,
                'bookingDateTime' => '2012-01-25 13:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'bookingId' => 185,
                'petId' => 3,
                'staffId' => 3,
                'bookingDateTime' => '2011-03-24 12:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'bookingId' => 186,
                'petId' => 31,
                'staffId' => 5,
                'bookingDateTime' => '2012-04-23 10:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'bookingId' => 187,
                'petId' => 97,
                'staffId' => 5,
                'bookingDateTime' => '2011-05-24 13:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'bookingId' => 188,
                'petId' => 98,
                'staffId' => 2,
                'bookingDateTime' => '2011-02-21 12:45:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'bookingId' => 189,
                'petId' => 95,
                'staffId' => 5,
                'bookingDateTime' => '2012-11-11 09:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'bookingId' => 190,
                'petId' => 71,
                'staffId' => 5,
                'bookingDateTime' => '2012-10-15 11:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'bookingId' => 191,
                'petId' => 74,
                'staffId' => 2,
                'bookingDateTime' => '2012-02-28 12:45:00',
                'symptoms' => 'vomiting',
                'treatments' => 'drugs',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'bookingId' => 192,
                'petId' => 16,
                'staffId' => 5,
                'bookingDateTime' => '2011-01-30 13:00:00',
                'symptoms' => 'flatulence',
                'treatments' => 'cuddles',
                'notes' => 'See again in 2 months',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'bookingId' => 193,
                'petId' => 88,
                'staffId' => 5,
                'bookingDateTime' => '2012-08-01 14:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => 'See again in 4 weeks',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            193 => 
            array (
                'bookingId' => 194,
                'petId' => 86,
                'staffId' => 5,
                'bookingDateTime' => '2011-06-18 12:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            194 => 
            array (
                'bookingId' => 195,
                'petId' => 22,
                'staffId' => 3,
                'bookingDateTime' => '2011-05-18 14:00:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            195 => 
            array (
                'bookingId' => 196,
                'petId' => 20,
                'staffId' => 3,
                'bookingDateTime' => '2011-11-07 10:30:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            196 => 
            array (
                'bookingId' => 197,
                'petId' => 78,
                'staffId' => 2,
                'bookingDateTime' => '2011-10-18 10:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            197 => 
            array (
                'bookingId' => 198,
                'petId' => 10,
                'staffId' => 2,
                'bookingDateTime' => '2012-10-09 13:15:00',
                'symptoms' => '',
                'treatments' => 'Routine vaccination',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            198 => 
            array (
                'bookingId' => 199,
                'petId' => 89,
                'staffId' => 3,
                'bookingDateTime' => '2012-07-04 16:00:00',
                'symptoms' => 'hair loss',
                'treatments' => 'invasive surgery',
                'notes' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}