<?php

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'customerId' => 1,
                'title' => 'Ms',
                'firstName' => 'Cara',
                'lastName' => 'Rojas',
                'gender' => 'F',
                'DOB' => '1977-08-26',
                'email' => 'crojas375@tpg.com.au',
            'phone1' => '(02) 4778 5452',
                'phone2' => '0424 677 626',
                'street1' => '',
                'street2' => '181 ONEY CIRCLE ',
                'suburb' => 'YELLOW ROCK',
                'state' => 'NSW',
                'postcode' => '2527',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'customerId' => 2,
                'title' => 'Sir',
                'firstName' => 'Isiah',
                'lastName' => 'Duke',
                'gender' => 'M',
                'DOB' => '1954-06-27',
                'email' => 'isiah.duke@optusnet.com.au',
            'phone1' => '(02) 4239 9759',
                'phone2' => '0416 858 673',
                'street1' => '',
                'street2' => '118 CAMEO COURT ',
                'suburb' => 'DONALD CREEK',
                'state' => 'NSW',
                'postcode' => '2350',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'customerId' => 3,
                'title' => 'Miss',
                'firstName' => 'Queen',
                'lastName' => 'Howe',
                'gender' => 'F',
                'DOB' => '1985-03-18',
                'email' => 'queen.howe@tpg.com.au',
            'phone1' => '(02) 4779 1377',
                'phone2' => '0432 168 361',
                'street1' => '',
                'street2' => '25 MULDROW STREET ',
                'suburb' => 'MILVALE',
                'state' => 'NSW',
                'postcode' => '2594',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'customerId' => 4,
                'title' => 'Ms',
                'firstName' => 'Gale',
                'lastName' => 'Newman',
                'gender' => 'F',
                'DOB' => '1965-09-12',
                'email' => 'gale.newman@gmail.com',
            'phone1' => '(02) 4545 2446',
                'phone2' => '0427 624 396',
                'street1' => '',
                'street2' => '51 PLATINUM CIRCLE ',
                'suburb' => 'DULGUIGAN',
                'state' => 'NSW',
                'postcode' => '2484',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'customerId' => 5,
                'title' => 'Mrs',
                'firstName' => 'Martha',
                'lastName' => 'Woodard',
                'gender' => 'F',
                'DOB' => '1953-03-20',
                'email' => 'martha.woodard@iinet.com.au',
            'phone1' => '(02) 4285 2551',
                'phone2' => '0421 784 818',
                'street1' => '',
                'street2' => '174 TIMBERWOLF CIRCLE ',
                'suburb' => 'ENFIELD SOUTH',
                'state' => 'NSW',
                'postcode' => '2133',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'customerId' => 6,
                'title' => 'Mr',
                'firstName' => 'Rick',
                'lastName' => 'Prince',
                'gender' => 'M',
                'DOB' => '1990-07-11',
                'email' => 'r.prince@hotmail.com',
            'phone1' => '(02) 4582 6459',
                'phone2' => '0434 525 675',
                'street1' => '',
                'street2' => '26/198 GOLDEN HILLS LANE ',
                'suburb' => 'PAMBULA BEACH',
                'state' => 'NSW',
                'postcode' => '2549',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'customerId' => 7,
                'title' => 'Mr',
                'firstName' => 'Mack',
                'lastName' => 'Carson',
                'gender' => 'M',
                'DOB' => '1967-09-26',
                'email' => 'mack@yahoo.com.au',
            'phone1' => '(02) 4382 2455',
                'phone2' => '0418 296 447',
                'street1' => '',
                'street2' => '141 ALDREN CIRCLE ',
                'suburb' => 'BROULEE',
                'state' => 'NSW',
                'postcode' => '2537',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'customerId' => 8,
                'title' => 'Mr',
                'firstName' => 'Willie',
                'lastName' => 'Burnett',
                'gender' => 'M',
                'DOB' => '1941-07-07',
                'email' => 'pryo_tick_killer@gmail.com',
            'phone1' => '(02) 4379 3727',
                'phone2' => '0415 157 696',
                'street1' => '',
                'street2' => '122 MARINO DRIVE ',
                'suburb' => 'BLAIR ATHOL',
                'state' => 'NSW',
                'postcode' => '2560',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'customerId' => 9,
                'title' => 'Mr',
                'firstName' => 'Isidro',
                'lastName' => 'Williams',
                'gender' => 'M',
                'DOB' => '1987-11-03',
                'email' => 'iwilliams72@hotmail.com',
            'phone1' => '(02) 4345 9845',
                'phone2' => '0403 675 211',
                'street1' => '',
                'street2' => '60 KRONOS DRIVE ',
                'suburb' => 'DRAKE VILLAGE',
                'state' => 'NSW',
                'postcode' => '2469',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'customerId' => 10,
                'title' => 'Mr',
                'firstName' => 'Leonard',
                'lastName' => 'Bernard',
                'gender' => 'M',
                'DOB' => '1935-06-28',
                'email' => 'l.bernard@gmail.com',
            'phone1' => '(02) 4253 4363',
                'phone2' => '0427 436 435',
                'street1' => '',
                'street2' => '124 CARAVELLE DRIVE ',
                'suburb' => 'EAST GRESFORD',
                'state' => 'NSW',
                'postcode' => '2311',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'customerId' => 11,
                'title' => 'Miss',
                'firstName' => 'Marianne',
                'lastName' => 'Cannon',
                'gender' => 'F',
                'DOB' => '1987-02-09',
                'email' => 'm.cannon@bigpond.com',
            'phone1' => '(02) 4727 2575',
                'phone2' => '0414 762 792',
                'street1' => '',
                'street2' => '14 LIMESTONE CIRCLE ',
                'suburb' => 'ERINA',
                'state' => 'NSW',
                'postcode' => '2250',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'customerId' => 12,
                'title' => 'Mr',
                'firstName' => 'Cory',
                'lastName' => 'Horn',
                'gender' => 'M',
                'DOB' => '1957-11-10',
                'email' => 'c.horn@bigpond.com',
            'phone1' => '(02) 4962 5235',
                'phone2' => '0425 211 128',
                'street1' => '',
                'street2' => '9/142 HELEN DRIVE ',
                'suburb' => 'MOGENDOURA',
                'state' => 'NSW',
                'postcode' => '2537',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'customerId' => 13,
                'title' => 'Miss',
                'firstName' => 'Maricela',
                'lastName' => 'Floyd',
                'gender' => 'F',
                'DOB' => '1937-12-08',
                'email' => 'maricela@bigpond.com',
            'phone1' => '(02) 4284 9532',
                'phone2' => '0416 435 744',
                'street1' => 'Unit 8 Level 1',
                'street2' => '125 OLD BIRCHWOOD LOOP ROAD ',
                'suburb' => 'KOOTINGAL',
                'state' => 'NSW',
                'postcode' => '2352',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'customerId' => 14,
                'title' => 'Dr',
                'firstName' => 'Josue',
                'lastName' => 'Potter',
                'gender' => 'M',
                'DOB' => '1945-01-20',
                'email' => 'jpotter151@mirkwoodproductions.com.au',
            'phone1' => '(02) 4348 6658',
                'phone2' => '0423 623 244',
                'street1' => 'Unit 8 Level 3',
                'street2' => '14 PARKSIDE DRIVE ',
                'suburb' => 'GUNDAROO',
                'state' => 'NSW',
                'postcode' => '2620',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'customerId' => 15,
                'title' => 'Ms',
                'firstName' => 'Ellen',
                'lastName' => 'Grant',
                'gender' => 'F',
                'DOB' => '1974-04-06',
                'email' => 'egrant146@hotmail.com',
            'phone1' => '(02) 4614 3278',
                'phone2' => '0425 632 382',
                'street1' => '',
                'street2' => '12/191 REVILLA CIRCLE ',
                'suburb' => 'VALLA BEACH',
                'state' => 'NSW',
                'postcode' => '2448',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'customerId' => 16,
                'title' => 'Mr',
                'firstName' => 'Salvatore',
                'lastName' => 'Pitts',
                'gender' => 'M',
                'DOB' => '1960-07-25',
                'email' => 's.pitts@bigpond.net.au',
            'phone1' => '(02) 4174 4745',
                'phone2' => '0428 464 261',
                'street1' => 'Unit 16 Level 1',
                'street2' => '157 AVION STREET ',
                'suburb' => 'ILARWILL',
                'state' => 'NSW',
                'postcode' => '2463',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'customerId' => 17,
                'title' => 'Ms',
                'firstName' => 'Carmella',
                'lastName' => 'Brady',
                'gender' => 'F',
                'DOB' => '1946-07-04',
                'email' => 'carmella@hotmail.com',
            'phone1' => '(02) 4677 1948',
                'phone2' => '0412 246 842',
                'street1' => '',
                'street2' => '28/176 WHISPERING SPRUCE CIRCLE ',
                'suburb' => 'MUNDONGO',
                'state' => 'NSW',
                'postcode' => '2720',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'customerId' => 18,
                'title' => 'Mr',
                'firstName' => 'Hiram',
                'lastName' => 'Tanner',
                'gender' => 'M',
                'DOB' => '1982-03-30',
                'email' => 'hiram.tanner@iinet.com.au',
            'phone1' => '(02) 4676 2444',
                'phone2' => '0418 127 993',
                'street1' => '',
                'street2' => '24 MEYER STREET ',
                'suburb' => 'BODALLA',
                'state' => 'NSW',
                'postcode' => '2545',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'customerId' => 19,
                'title' => 'Mr',
                'firstName' => 'Marco',
                'lastName' => 'Burke',
                'gender' => 'M',
                'DOB' => '1950-02-26',
                'email' => 'marco.burke@iinet.com.au',
            'phone1' => '(02) 4558 5587',
                'phone2' => '0417 227 826',
                'street1' => '',
                'street2' => '128 BIRCHWOOD SPUR ROAD ',
                'suburb' => 'TYALGUM',
                'state' => 'NSW',
                'postcode' => '2484',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'customerId' => 20,
                'title' => 'Mr',
                'firstName' => 'Adolfo',
                'lastName' => 'Gonzales',
                'gender' => 'M',
                'DOB' => '1967-11-12',
                'email' => 'adolfo.gonzales@hotmail.com',
            'phone1' => '(02) 4617 2812',
                'phone2' => '0403 682 237',
                'street1' => '',
                'street2' => '10 HIGHLAND STREET ',
                'suburb' => 'ETTRICK',
                'state' => 'NSW',
                'postcode' => '2474',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'customerId' => 21,
                'title' => 'Mrs',
                'firstName' => 'Vanessa',
                'lastName' => 'Jacobs',
                'gender' => 'F',
                'DOB' => '1941-12-04',
                'email' => 'vanessa.jacobs@hotmail.com',
            'phone1' => '(02) 4388 8786',
                'phone2' => '0428 377 178',
                'street1' => '',
                'street2' => '170 KAHILTNA DRIVE ',
                'suburb' => 'LONG POINT',
                'state' => 'NSW',
                'postcode' => '2564',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'customerId' => 22,
                'title' => 'Ms',
                'firstName' => 'Henrietta',
                'lastName' => 'Brown',
                'gender' => 'F',
                'DOB' => '1958-01-22',
                'email' => 'hbrown192@tpg.com.au',
            'phone1' => '(02) 4313 5228',
                'phone2' => '0434 684 748',
                'street1' => '',
                'street2' => '89 ROSALIND LOOP ',
                'suburb' => 'BLACKTOWN WESTPOINT',
                'state' => 'NSW',
                'postcode' => '2148',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'customerId' => 23,
                'title' => 'Mr',
                'firstName' => 'Johnathan',
                'lastName' => 'Ballard',
                'gender' => 'M',
                'DOB' => '1971-05-21',
                'email' => 'johnathan.ballard@gmail.com',
            'phone1' => '(02) 4968 1825',
                'phone2' => '0418 926 372',
                'street1' => 'Unit 3 Level 3',
                'street2' => '148 HIALEAH DRIVE ',
                'suburb' => 'EASTWOOD',
                'state' => 'NSW',
                'postcode' => '2122',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'customerId' => 24,
                'title' => 'Ms',
                'firstName' => 'Dollie',
                'lastName' => 'Austin',
                'gender' => 'F',
                'DOB' => '1956-10-02',
                'email' => 'daustin471@optusnet.com.au',
            'phone1' => '(02) 4817 6738',
                'phone2' => '0428 898 385',
                'street1' => '',
                'street2' => '101 TOPHAND TRAILER COURT ',
                'suburb' => 'GWYNNEVILLE',
                'state' => 'NSW',
                'postcode' => '2500',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'customerId' => 25,
                'title' => 'Dr',
                'firstName' => 'Roger',
                'lastName' => 'Mercer',
                'gender' => 'M',
                'DOB' => '1980-09-27',
                'email' => 'roger@gmail.com',
            'phone1' => '(02) 4419 7515',
                'phone2' => '0422 727 842',
                'street1' => '',
                'street2' => '117 BYERS LANE ',
                'suburb' => 'ISABELLA PLAINS',
                'state' => 'NSW',
                'postcode' => '2905',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'customerId' => 26,
                'title' => 'Mr',
                'firstName' => 'Antwan',
                'lastName' => 'Griffith',
                'gender' => 'M',
                'DOB' => '1977-07-20',
                'email' => 'antwan.griffith@iinet.com.au',
            'phone1' => '(02) 4768 8366',
                'phone2' => '0431 857 258',
                'street1' => '',
                'street2' => '24 MOUNTAIN ROAD ',
                'suburb' => 'TARALGA',
                'state' => 'NSW',
                'postcode' => '2580',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'customerId' => 27,
                'title' => 'Ms',
                'firstName' => 'Susanne',
                'lastName' => 'Banks',
                'gender' => 'F',
                'DOB' => '1970-12-07',
                'email' => 's.banks@hotmail.com',
            'phone1' => '(02) 4212 7193',
                'phone2' => '0414 371 863',
                'street1' => '',
                'street2' => '103 WATERFRONT LANE ',
                'suburb' => 'LINDENDALE',
                'state' => 'NSW',
                'postcode' => '2480',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'customerId' => 28,
                'title' => 'Mr',
                'firstName' => 'Alvaro',
                'lastName' => 'Gilbert',
                'gender' => 'M',
                'DOB' => '1974-11-27',
                'email' => 'a.gilbert@bigpond.com',
            'phone1' => '(02) 4753 7226',
                'phone2' => '0416 459 566',
                'street1' => '',
                'street2' => '173 NEW LONDON COURT ',
                'suburb' => 'BOWEN MOUNTAIN',
                'state' => 'NSW',
                'postcode' => '2753',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'customerId' => 29,
                'title' => 'Ms',
                'firstName' => 'Georgette',
                'lastName' => 'Mcdaniel',
                'gender' => 'F',
                'DOB' => '1950-04-04',
                'email' => 'gmcdaniel97@bigpond.com',
            'phone1' => '(02) 4573 9265',
                'phone2' => '0402 723 437',
                'street1' => '',
                'street2' => '146 SAINT JAMES STREET ',
                'suburb' => 'PEMULWUY',
                'state' => 'NSW',
                'postcode' => '2145',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'customerId' => 30,
                'title' => 'Ms',
                'firstName' => 'Alyson',
                'lastName' => 'Mcfadden',
                'gender' => 'F',
                'DOB' => '1992-03-14',
                'email' => 'alyson.mcfadden@gmail.com',
            'phone1' => '(02) 4688 2332',
                'phone2' => '0428 752 252',
                'street1' => '',
                'street2' => '90 MYRTLE DRIVE ',
                'suburb' => 'QUANDIALLA',
                'state' => 'NSW',
                'postcode' => '2721',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'customerId' => 31,
                'title' => 'Mr',
                'firstName' => 'Devin',
                'lastName' => 'Reese',
                'gender' => 'M',
                'DOB' => '1992-06-14',
                'email' => 'devin.reese@gmail.com',
            'phone1' => '(02) 4457 3637',
                'phone2' => '0405 132 526',
                'street1' => '',
                'street2' => '99 SHIVALIK DRIVE ',
                'suburb' => 'COURABYRA',
                'state' => 'NSW',
                'postcode' => '2653',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'customerId' => 32,
                'title' => 'Mr',
                'firstName' => 'Phil',
                'lastName' => 'Guerra',
                'gender' => 'M',
                'DOB' => '1960-12-08',
                'email' => 'p.guerra@bigpond.net.au',
            'phone1' => '(02) 4557 3267',
                'phone2' => '0415 897 433',
                'street1' => '',
                'street2' => '80 BLUEGRASS CIRCLE ',
                'suburb' => 'DUNMORE',
                'state' => 'NSW',
                'postcode' => '2529',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'customerId' => 33,
                'title' => 'Mr',
                'firstName' => 'Angelo',
                'lastName' => 'Kelly',
                'gender' => 'M',
                'DOB' => '1982-05-13',
                'email' => 'a.kelly@gmail.com',
            'phone1' => '(02) 4253 4263',
                'phone2' => '0427 436 435',
                'street1' => '',
                'street2' => '164 BLACK BEAR CIRCLE ',
                'suburb' => 'ROYAL EXCHANGE',
                'state' => 'NSW',
                'postcode' => '1225',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'customerId' => 34,
                'title' => 'Ms',
                'firstName' => 'Lola',
                'lastName' => 'Trevino',
                'gender' => 'F',
                'DOB' => '1972-01-10',
                'email' => 'lola@bigpond.net.au',
            'phone1' => '(02) 4383 8368',
                'phone2' => '0426 587 382',
                'street1' => '',
                'street2' => '12/182 ESSEX PARK DRIVE ',
                'suburb' => 'CAMBEWARRA',
                'state' => 'NSW',
                'postcode' => '2540',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'customerId' => 35,
                'title' => 'Mr',
                'firstName' => 'Travis',
                'lastName' => 'Mcgee',
                'gender' => 'M',
                'DOB' => '1952-09-03',
                'email' => 'travis@bigpond.net.au',
            'phone1' => '(02) 4474 9381',
                'phone2' => '0415 498 889',
                'street1' => '',
                'street2' => '184 SHELTIE AVENUE ',
                'suburb' => 'SCHEYVILLE',
                'state' => 'NSW',
                'postcode' => '2756',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'customerId' => 36,
                'title' => 'Mrs',
                'firstName' => 'Abigail',
                'lastName' => 'Lowery',
                'gender' => 'F',
                'DOB' => '1971-03-27',
                'email' => 'alowery499@gmail.com',
            'phone1' => '(02) 4184 8532',
                'phone2' => '0433 293 422',
                'street1' => '',
                'street2' => '33 EGLOFF DRIVE ',
                'suburb' => 'OATLANDS',
                'state' => 'NSW',
                'postcode' => '2117',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'customerId' => 37,
                'title' => 'Miss',
                'firstName' => 'Goldie',
                'lastName' => 'Flores',
                'gender' => 'F',
                'DOB' => '1962-11-19',
                'email' => 'goldie.flores@bigpond.com',
            'phone1' => '(02) 4178 4218',
                'phone2' => '0413 625 668',
                'street1' => '',
                'street2' => '83 MILE HI WAY ',
                'suburb' => 'MASCOT',
                'state' => 'NSW',
                'postcode' => '1460',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'customerId' => 38,
                'title' => 'Miss',
                'firstName' => 'Erin',
                'lastName' => 'Beasley',
                'gender' => 'F',
                'DOB' => '1957-11-02',
                'email' => 'erin@bigpond.com',
            'phone1' => '(02) 4714 7217',
                'phone2' => '0416 666 434',
                'street1' => '',
                'street2' => '10/134 SOUTH AIRPARK DRIVE ',
                'suburb' => 'BURRA',
                'state' => 'NSW',
                'postcode' => '2620',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'customerId' => 39,
                'title' => 'Ms',
                'firstName' => 'Natalie',
                'lastName' => 'Fields',
                'gender' => 'F',
                'DOB' => '1963-05-21',
                'email' => 'n.fields@gmail.com',
            'phone1' => '(02) 4932 7558',
                'phone2' => '0415 794 642',
                'street1' => '',
                'street2' => '31 BRUDNE ROAD ',
                'suburb' => 'ALLAWAH',
                'state' => 'NSW',
                'postcode' => '2218',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'customerId' => 40,
                'title' => 'Ms',
                'firstName' => 'Peggy',
                'lastName' => 'Bennett',
                'gender' => 'F',
                'DOB' => '1956-10-07',
                'email' => 'p.bennett@hotmail.com',
            'phone1' => '(02) 4484 6587',
                'phone2' => '0416 298 257',
                'street1' => '',
                'street2' => '103 ANTLER LANE ',
                'suburb' => 'ROYAL EXCHANGE',
                'state' => 'NSW',
                'postcode' => '1225',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'customerId' => 41,
                'title' => 'Mr',
                'firstName' => 'Alphonse',
                'lastName' => 'Griffin',
                'gender' => 'M',
                'DOB' => '1960-09-26',
                'email' => 'a.griffin@tyasa.com.au',
            'phone1' => '(02) 4945 6492',
                'phone2' => '0412 378 957',
                'street1' => '',
                'street2' => '6/5 LAKE GEORGE DRIVE ',
                'suburb' => 'MONA VALE',
                'state' => 'NSW',
                'postcode' => '1660',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'customerId' => 42,
                'title' => 'Miss',
                'firstName' => 'Phyllis',
                'lastName' => 'Spencer',
                'gender' => 'F',
                'DOB' => '1981-08-05',
                'email' => 'phyllis.spencer@hotmail.com',
            'phone1' => '(02) 4641 2512',
                'phone2' => '0413 937 734',
                'street1' => '',
                'street2' => '88 DONALD PLACE ',
                'suburb' => 'BELIMBLA PARK',
                'state' => 'NSW',
                'postcode' => '2570',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'customerId' => 43,
                'title' => 'Miss',
                'firstName' => 'Beth',
                'lastName' => 'Keith',
                'gender' => 'F',
                'DOB' => '1983-12-28',
                'email' => 'b.keith@yahoo.com.au',
            'phone1' => '(02) 4932 5253',
                'phone2' => '0415 571 455',
                'street1' => '',
                'street2' => '192 DANE COURT ',
                'suburb' => 'WOOLI',
                'state' => 'NSW',
                'postcode' => '2462',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'customerId' => 44,
                'title' => 'Mrs',
                'firstName' => 'Traci',
                'lastName' => 'Haynes',
                'gender' => 'F',
                'DOB' => '1941-04-25',
                'email' => 'traci.haynes@hotmail.com',
            'phone1' => '(02) 4129 6555',
                'phone2' => '0423 458 446',
                'street1' => '',
                'street2' => '16 PATRICIA LANE ',
                'suburb' => 'BANKSTOWN SQUARE',
                'state' => 'NSW',
                'postcode' => '2200',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'customerId' => 45,
                'title' => 'Mr',
                'firstName' => 'Darrin',
                'lastName' => 'Cannon',
                'gender' => 'M',
                'DOB' => '1942-02-19',
                'email' => 'dcannon307@optusnet.com.au',
            'phone1' => '(02) 4476 4785',
                'phone2' => '0423 389 372',
                'street1' => '',
                'street2' => '189 BARROW STREET ',
                'suburb' => 'INGLEBURN',
                'state' => 'NSW',
                'postcode' => '2565',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'customerId' => 46,
                'title' => 'Ms',
                'firstName' => 'Melinda',
                'lastName' => 'Snow',
                'gender' => 'F',
                'DOB' => '1945-06-12',
                'email' => 'melinda@hotmail.com',
            'phone1' => '(02) 4447 5677',
                'phone2' => '0433 377 849',
                'street1' => '',
                'street2' => '111 WHITEHALL ROAD ',
                'suburb' => 'TWEED HEADS WEST',
                'state' => 'NSW',
                'postcode' => '2485',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'customerId' => 47,
                'title' => 'Mrs',
                'firstName' => 'Ophelia',
                'lastName' => 'Wilkins',
                'gender' => 'F',
                'DOB' => '1957-06-11',
                'email' => 'owilkins269@iinet.com.au',
            'phone1' => '(02) 4554 5323',
                'phone2' => '0424 144 547',
                'street1' => '',
                'street2' => '54 SPECKING AVENUE ',
                'suburb' => 'GROGAN',
                'state' => 'NSW',
                'postcode' => '2666',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'customerId' => 48,
                'title' => 'Mr',
                'firstName' => 'Willie',
                'lastName' => 'Nukeit',
                'gender' => 'M',
                'DOB' => '1959-09-06',
                'email' => '15_seconds_on_high@gmail.com',
            'phone1' => '(02) 4468 5531',
                'phone2' => '0429 352 523',
                'street1' => '',
                'street2' => '13/42 SKY CIRCLE ',
                'suburb' => 'RAYMOND TERRACE EAST',
                'state' => 'NSW',
                'postcode' => '2324',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'customerId' => 49,
                'title' => 'Mrs',
                'firstName' => 'Dorthy',
                'lastName' => 'Harrington',
                'gender' => 'F',
                'DOB' => '1972-08-31',
                'email' => 'd.harrington@bigpond.net.au',
            'phone1' => '(02) 4734 3568',
                'phone2' => '0413 566 257',
                'street1' => '',
                'street2' => '107 STANLEY DRIVE ',
                'suburb' => 'CROWTHER',
                'state' => 'NSW',
                'postcode' => '2803',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'customerId' => 50,
                'title' => 'Mr',
                'firstName' => 'Dewayne',
                'lastName' => 'Mccormick',
                'gender' => 'M',
                'DOB' => '1979-10-14',
                'email' => 'dewayne@bigpond.com',
            'phone1' => '(02) 4128 6846',
                'phone2' => '0429 128 465',
                'street1' => '',
                'street2' => '88 CAMPBELL AIRSTRIP ROAD ',
                'suburb' => 'WEST CHATSWOOD',
                'state' => 'NSW',
                'postcode' => '1515',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'customerId' => 51,
                'title' => 'Mr',
                'firstName' => 'Ronny',
                'lastName' => 'Lancaster',
                'gender' => 'M',
                'DOB' => '1974-09-28',
                'email' => 'r.lancaster@bigpond.com',
            'phone1' => '(02) 4482 8625',
                'phone2' => '0424 931 262',
                'street1' => '',
                'street2' => '172 CALAMITY COURT ',
                'suburb' => 'MONGARLOWE',
                'state' => 'NSW',
                'postcode' => '2622',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'customerId' => 52,
                'title' => 'Mr',
                'firstName' => 'Glen',
                'lastName' => 'Cameron',
                'gender' => 'M',
                'DOB' => '1963-10-31',
                'email' => 'gcameron341@hotmail.com',
            'phone1' => '(02) 4682 5867',
                'phone2' => '0412 774 781',
                'street1' => '',
                'street2' => '191 SPRUCE RUN CIRCLE ',
                'suburb' => 'WALLABI POINT',
                'state' => 'NSW',
                'postcode' => '2430',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'customerId' => 53,
                'title' => 'Ms',
                'firstName' => 'Cristina',
                'lastName' => 'Vance',
                'gender' => 'F',
                'DOB' => '1956-07-20',
                'email' => 'cristina@gmail.com',
            'phone1' => '(02) 4349 3356',
                'phone2' => '0425 932 855',
                'street1' => '',
                'street2' => '199 KATRINA CIRCLE ',
                'suburb' => 'MIRRABOOKA',
                'state' => 'NSW',
                'postcode' => '2264',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'customerId' => 54,
                'title' => 'Miss',
                'firstName' => 'Tasha',
                'lastName' => 'Hancock',
                'gender' => 'F',
                'DOB' => '1944-08-21',
                'email' => 'thancock215@hotmail.com',
            'phone1' => '(02) 4492 4838',
                'phone2' => '0416 278 728',
                'street1' => '',
                'street2' => '103 PORTAGE DRIVE ',
                'suburb' => 'PALMDALE',
                'state' => 'NSW',
                'postcode' => '2258',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'customerId' => 55,
                'title' => 'Mr',
                'firstName' => 'Willie',
                'lastName' => 'Baggitt',
                'gender' => 'M',
                'DOB' => '1978-08-22',
                'email' => 'listen_for_the_pop@gmail.com',
            'phone1' => '(02) 4234 8734',
                'phone2' => '0432 564 188',
                'street1' => '',
                'street2' => '104 KITZBUHEL ROAD ',
                'suburb' => 'RAPPVILLE',
                'state' => 'NSW',
                'postcode' => '2469',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'customerId' => 56,
                'title' => 'Mrs',
                'firstName' => 'Patricia',
                'lastName' => 'Bean',
                'gender' => 'F',
                'DOB' => '1942-09-29',
                'email' => 'patricia.bean@mirkwoodproductions.com.au',
            'phone1' => '(02) 4728 9738',
                'phone2' => '0414 183 182',
                'street1' => '',
                'street2' => '176 CAMELOT DRIVE ',
                'suburb' => 'SMITHS CREEK',
                'state' => 'NSW',
                'postcode' => '2474',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'customerId' => 57,
                'title' => 'Mr',
                'firstName' => 'Normand',
                'lastName' => 'Mcmahon',
                'gender' => 'M',
                'DOB' => '1948-11-10',
                'email' => 'normand.mcmahon@hotmail.com',
            'phone1' => '(02) 4847 4724',
                'phone2' => '0402 943 746',
                'street1' => 'Unit 12 Level 1',
                'street2' => '143 GREATLAND DRIVE ',
                'suburb' => 'CENTRAL MANGROVE',
                'state' => 'NSW',
                'postcode' => '2250',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'customerId' => 58,
                'title' => 'Ms',
                'firstName' => 'Clarice',
                'lastName' => 'Riddle',
                'gender' => 'F',
                'DOB' => '1982-09-25',
                'email' => 'clarice.riddle@gmail.com',
            'phone1' => '(02) 4838 5745',
                'phone2' => '0432 854 445',
                'street1' => '',
                'street2' => '4 WOODSTOCK CIRCLE ',
                'suburb' => 'SPLITTERS CREEK',
                'state' => 'NSW',
                'postcode' => '2640',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'customerId' => 59,
                'title' => 'Mr',
                'firstName' => 'Scott',
                'lastName' => 'Watkins',
                'gender' => 'M',
                'DOB' => '1948-01-26',
                'email' => 's.watkins@yahoo.com.au',
            'phone1' => '(02) 4675 1628',
                'phone2' => '0425 976 817',
                'street1' => '',
                'street2' => '163 GALLOWAY LOOP ',
                'suburb' => 'SOUTHGATE',
                'state' => 'NSW',
                'postcode' => '2460',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'customerId' => 60,
                'title' => 'Prof',
                'firstName' => 'Sonja',
                'lastName' => 'Carr',
                'gender' => 'F',
                'DOB' => '1949-11-23',
                'email' => 'sonja.carr@hotmail.com',
            'phone1' => '(02) 4464 5976',
                'phone2' => '0428 837 333',
                'street1' => '',
                'street2' => '10 TIDEVIEW DRIVE ',
                'suburb' => 'OLD GUILDFORD',
                'state' => 'NSW',
                'postcode' => '2161',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'customerId' => 61,
                'title' => 'Mr',
                'firstName' => 'Rolando',
                'lastName' => 'Gamble',
                'gender' => 'M',
                'DOB' => '1981-11-29',
                'email' => 'rolando.gamble@gmail.com',
            'phone1' => '(02) 4247 2542',
                'phone2' => '0429 991 767',
                'street1' => '',
                'street2' => '18/172 ED STREET ',
                'suburb' => 'CARINGBAH',
                'state' => 'NSW',
                'postcode' => '1495',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'customerId' => 62,
                'title' => 'Mr',
                'firstName' => 'Rocky',
                'lastName' => 'Petersen',
                'gender' => 'M',
                'DOB' => '1940-03-20',
                'email' => 'rocky@optusnet.com.au',
            'phone1' => '(02) 4687 5225',
                'phone2' => '0402 461 317',
                'street1' => '',
                'street2' => '115 CAPE NOBLE CIRCLE ',
                'suburb' => 'KIAMA DOWNS',
                'state' => 'NSW',
                'postcode' => '2533',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'customerId' => 63,
                'title' => 'Mr',
                'firstName' => 'Hiram',
                'lastName' => 'Middleton',
                'gender' => 'M',
                'DOB' => '1979-02-07',
                'email' => 'hmiddleton22@tpg.com.au',
            'phone1' => '(02) 4513 2558',
                'phone2' => '0417 657 247',
                'street1' => '',
                'street2' => '90 DEWEY CIRCLE ',
                'suburb' => 'BEROWRA WATERS',
                'state' => 'NSW',
                'postcode' => '2082',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'customerId' => 64,
                'title' => 'Miss',
                'firstName' => 'Valarie',
                'lastName' => 'Elliott',
                'gender' => 'F',
                'DOB' => '1989-04-12',
                'email' => 'v.elliott@gmail.com',
            'phone1' => '(02) 4779 7455',
                'phone2' => '0426 234 822',
                'street1' => '',
                'street2' => '2 BOYSEN BERRY PLACE ',
                'suburb' => 'POINT PIPER',
                'state' => 'NSW',
                'postcode' => '2027',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'customerId' => 65,
                'title' => 'Mr',
                'firstName' => 'Toby',
                'lastName' => 'Booth',
                'gender' => 'M',
                'DOB' => '1968-05-09',
                'email' => 'toby@mirkwoodproductions.com.au',
            'phone1' => '(02) 4672 6719',
                'phone2' => '0428 448 138',
                'street1' => '',
                'street2' => '182 HASTINGS LANE ',
                'suburb' => 'WILLIAMSDALE',
                'state' => 'NSW',
                'postcode' => '2620',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'customerId' => 66,
                'title' => 'Prof',
                'firstName' => 'Hunter',
                'lastName' => 'Obrien',
                'gender' => 'M',
                'DOB' => '1956-04-12',
                'email' => 'hobrien364@gmail.com',
            'phone1' => '(02) 4273 8232',
                'phone2' => '0416 922 476',
                'street1' => '',
                'street2' => '186 GARNET STREET ',
                'suburb' => 'WEETANGERA',
                'state' => 'NSW',
                'postcode' => '2614',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'customerId' => 67,
                'title' => 'Mr',
                'firstName' => 'Kurt',
                'lastName' => 'Compton',
                'gender' => 'M',
                'DOB' => '1993-07-02',
                'email' => 'k.compton@hotmail.com',
            'phone1' => '(02) 4988 8967',
                'phone2' => '0404 883 918',
                'street1' => '',
                'street2' => '166 GOLD CIRCLE ',
                'suburb' => 'WHITE CLIFFS',
                'state' => 'NSW',
                'postcode' => '2836',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'customerId' => 68,
                'title' => 'Mr',
                'firstName' => 'Luciano',
                'lastName' => 'Hodge',
                'gender' => 'M',
                'DOB' => '1965-06-01',
                'email' => 'luciano@mirkwoodproductions.com.au',
            'phone1' => '(02) 4934 2288',
                'phone2' => '0415 736 372',
                'street1' => '',
                'street2' => '22 MISTY SPRINGS COURT ',
                'suburb' => 'BLAIRMOUNT',
                'state' => 'NSW',
                'postcode' => '2559',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'customerId' => 69,
                'title' => 'Mr',
                'firstName' => 'Randy',
                'lastName' => 'Gonzalez',
                'gender' => 'M',
                'DOB' => '1938-01-12',
                'email' => 'randy.gonzalez@tpg.com.au',
            'phone1' => '(02) 4456 6722',
                'phone2' => '0426 738 474',
                'street1' => 'Unit 3 Level 2',
                'street2' => '48 PASO PLACE ',
                'suburb' => 'BUNGAWALBIN',
                'state' => 'NSW',
                'postcode' => '2469',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'customerId' => 70,
                'title' => 'Mr',
                'firstName' => 'Monroe',
                'lastName' => 'Wilson',
                'gender' => 'M',
                'DOB' => '1945-02-24',
                'email' => 'monroe.wilson@mirkwoodproductions.com.au',
            'phone1' => '(02) 4664 3495',
                'phone2' => '0415 665 952',
                'street1' => '',
                'street2' => '118 MOUNTAINMAN LOOP ',
                'suburb' => 'WEST WYALONG',
                'state' => 'NSW',
                'postcode' => '2671',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'customerId' => 71,
                'title' => 'Miss',
                'firstName' => 'Simone',
                'lastName' => 'Collier',
                'gender' => 'F',
                'DOB' => '1940-02-09',
                'email' => 'simone.collier@hotmail.com',
            'phone1' => '(02) 4966 4262',
                'phone2' => '0416 364 486',
                'street1' => '',
                'street2' => '5/144 ROSEMONT DRIVE ',
                'suburb' => 'NORTH BALGOWLAH',
                'state' => 'NSW',
                'postcode' => '2093',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'customerId' => 72,
                'title' => 'Ms',
                'firstName' => 'Alisha',
                'lastName' => 'Vaughan',
                'gender' => 'F',
                'DOB' => '1945-08-27',
                'email' => 'alisha@gmail.com',
            'phone1' => '(02) 4324 5722',
                'phone2' => '0415 514 624',
                'street1' => '',
                'street2' => '87 GLENN NB OFF S BIRCHWOOD LOOP RAMP ',
                'suburb' => 'PACIFIC PALMS',
                'state' => 'NSW',
                'postcode' => '2428',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'customerId' => 73,
                'title' => 'Mr',
                'firstName' => 'Willie',
                'lastName' => 'Tweezeit',
                'gender' => 'M',
                'DOB' => '1984-07-15',
                'email' => 'grab_life_by_the_head@gmail.com',
            'phone1' => '(02) 4772 2315',
                'phone2' => '0426 412 512',
                'street1' => '',
                'street2' => '80 HOSKEN STREET ',
                'suburb' => 'MACQUARIE PARK',
                'state' => 'NSW',
                'postcode' => '2113',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'customerId' => 74,
                'title' => 'Mr',
                'firstName' => 'Louie',
                'lastName' => 'Lindsay',
                'gender' => 'M',
                'DOB' => '1980-07-26',
                'email' => 'l.lindsay@gmail.com',
            'phone1' => '(02) 4663 8289',
                'phone2' => '0419 324 483',
                'street1' => '',
                'street2' => '185 HILLCREST DRIVE ',
                'suburb' => 'LISMORE',
                'state' => 'NSW',
                'postcode' => '2480',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'customerId' => 75,
                'title' => 'Miss',
                'firstName' => 'Bettie',
                'lastName' => 'Mathis',
                'gender' => 'F',
                'DOB' => '1951-03-14',
                'email' => 'bettie.mathis@mirkwoodproductions.com.au',
            'phone1' => '(02) 4794 3885',
                'phone2' => '0431 296 777',
                'street1' => '',
                'street2' => '69 CHAPEL DRIVE ',
                'suburb' => 'HUMULA',
                'state' => 'NSW',
                'postcode' => '2652',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'customerId' => 76,
                'title' => 'Dr',
                'firstName' => 'Kay',
                'lastName' => 'Blake',
                'gender' => 'F',
                'DOB' => '1961-06-19',
                'email' => 'k.blake@hotmail.com',
            'phone1' => '(02) 4677 6243',
                'phone2' => '0436 616 698',
                'street1' => '',
                'street2' => '24 BRIDGER PLACE ',
                'suburb' => 'WARIALDA RAIL',
                'state' => 'NSW',
                'postcode' => '2402',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}