<?php

use Illuminate\Database\Seeder;

class PetsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pets')->delete();
        
        \DB::table('pets')->insert(array (
            0 => 
            array (
                'petId' => 1,
                'petName' => 'Nkala',
                'species' => 'Cat',
                'breed' => 'DLH',
                'DOB' => '2011-04-13',
                'gender' => 'F',
                'weight' => 3.6,
                'customerId' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'petId' => 2,
                'petName' => 'Charlie',
                'species' => 'Cat',
                'breed' => 'Burmese',
                'DOB' => '2002-03-16',
                'gender' => 'M',
                'weight' => 4.3,
                'customerId' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'petId' => 3,
                'petName' => 'Darky',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2010-12-20',
                'gender' => 'M',
                'weight' => 6.8,
                'customerId' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'petId' => 4,
                'petName' => 'Kitty',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2008-01-22',
                'gender' => 'M',
                'weight' => 7.5,
                'customerId' => 63,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'petId' => 5,
                'petName' => 'Stripey',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '1999-04-14',
                'gender' => 'M',
                'weight' => 6.9,
                'customerId' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'petId' => 6,
                'petName' => 'Happy',
                'species' => 'Cat',
                'breed' => 'Persian',
                'DOB' => '2012-04-12',
                'gender' => 'M',
                'weight' => 8.1,
                'customerId' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'petId' => 7,
                'petName' => 'Bichel',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2004-12-29',
                'gender' => 'M',
                'weight' => 3.0,
                'customerId' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'petId' => 8,
                'petName' => 'Trouble',
                'species' => 'Cat',
                'breed' => 'DLH',
                'DOB' => '1998-12-12',
                'gender' => 'M',
                'weight' => 6.7,
                'customerId' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'petId' => 9,
                'petName' => 'Rupert',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2002-08-10',
                'gender' => 'M',
                'weight' => 5.4,
                'customerId' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'petId' => 10,
                'petName' => 'Lucky',
                'species' => 'Cat',
                'breed' => 'Siamese',
                'DOB' => '2005-05-03',
                'gender' => 'M',
                'weight' => 7.4,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'petId' => 11,
                'petName' => 'Jemima',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2006-07-18',
                'gender' => 'F',
                'weight' => 7.2,
                'customerId' => 69,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'petId' => 12,
                'petName' => 'Nathan',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2005-08-05',
                'gender' => 'M',
                'weight' => 6.1,
                'customerId' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'petId' => 13,
                'petName' => 'Harold',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2012-06-12',
                'gender' => 'M',
                'weight' => 5.8,
                'customerId' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'petId' => 14,
                'petName' => 'Tabitha',
                'species' => 'Cat',
                'breed' => 'Persian',
                'DOB' => '2006-08-29',
                'gender' => 'F',
                'weight' => 4.3,
                'customerId' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'petId' => 15,
                'petName' => 'Diggeden',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2003-04-20',
                'gender' => 'M',
                'weight' => 6.8,
                'customerId' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'petId' => 16,
                'petName' => 'Tigger',
                'species' => 'Cat',
                'breed' => 'Burmese',
                'DOB' => '2008-11-06',
                'gender' => 'M',
                'weight' => 5.7,
                'customerId' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'petId' => 17,
                'petName' => 'Sadza',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2011-10-01',
                'gender' => 'M',
                'weight' => 5.9,
                'customerId' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'petId' => 18,
                'petName' => 'Gravy',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2001-06-10',
                'gender' => 'M',
                'weight' => 3.9,
                'customerId' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'petId' => 19,
                'petName' => 'Phoebe',
                'species' => 'Cat',
                'breed' => 'Persian',
                'DOB' => '2007-06-24',
                'gender' => 'F',
                'weight' => 7.2,
                'customerId' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'petId' => 20,
                'petName' => 'Meow-Meow',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2004-12-09',
                'gender' => 'F',
                'weight' => 4.4,
                'customerId' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'petId' => 21,
                'petName' => 'Puffles',
                'species' => 'Cat',
                'breed' => 'Siamese',
                'DOB' => '2008-05-31',
                'gender' => 'F',
                'weight' => 3.9,
                'customerId' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'petId' => 22,
                'petName' => 'Splat',
                'species' => 'Cat',
                'breed' => 'Persian',
                'DOB' => '2006-06-09',
                'gender' => 'F',
                'weight' => 7.8,
                'customerId' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'petId' => 23,
                'petName' => 'Paw Thing',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2009-05-24',
                'gender' => 'F',
                'weight' => 3.4,
                'customerId' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'petId' => 24,
                'petName' => 'Verushka',
                'species' => 'Cat',
                'breed' => 'Russian Blue',
                'DOB' => '1998-11-28',
                'gender' => 'F',
                'weight' => 5.1,
                'customerId' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'petId' => 25,
                'petName' => 'Gobbles',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2006-03-24',
                'gender' => 'M',
                'weight' => 3.6,
                'customerId' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'petId' => 26,
                'petName' => 'Fat Fred',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2006-08-02',
                'gender' => 'M',
                'weight' => 5.5,
                'customerId' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'petId' => 27,
                'petName' => 'Blimpie',
                'species' => 'Cat',
                'breed' => 'Burmese',
                'DOB' => '2000-03-22',
                'gender' => 'M',
                'weight' => 7.5,
                'customerId' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'petId' => 28,
                'petName' => 'Fred',
                'species' => 'Cat',
                'breed' => 'Siamese',
                'DOB' => '2001-03-03',
                'gender' => 'M',
                'weight' => 4.2,
                'customerId' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'petId' => 29,
                'petName' => 'Frankie',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2009-05-19',
                'gender' => 'M',
                'weight' => 7.1,
                'customerId' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'petId' => 30,
                'petName' => 'Sooty',
                'species' => 'Cat',
                'breed' => 'DLH',
                'DOB' => '2004-10-02',
                'gender' => 'M',
                'weight' => 7.0,
                'customerId' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'petId' => 31,
                'petName' => 'Geeves',
                'species' => 'Cat',
                'breed' => 'DLH',
                'DOB' => '2006-12-06',
                'gender' => 'M',
                'weight' => 6.9,
                'customerId' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'petId' => 32,
                'petName' => 'Miranda',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2005-05-20',
                'gender' => 'F',
                'weight' => 7.8,
                'customerId' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'petId' => 33,
                'petName' => 'Cazza',
                'species' => 'Cat',
                'breed' => 'DLH',
                'DOB' => '2011-04-15',
                'gender' => 'F',
                'weight' => 6.2,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'petId' => 34,
                'petName' => 'Abby',
                'species' => 'Cat',
                'breed' => 'Munchkin',
                'DOB' => '1999-02-10',
                'gender' => 'F',
                'weight' => 7.4,
                'customerId' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'petId' => 35,
                'petName' => 'Whiskers',
                'species' => 'Cat',
                'breed' => 'DSH',
                'DOB' => '2000-04-05',
                'gender' => 'M',
                'weight' => 3.1,
                'customerId' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'petId' => 36,
                'petName' => 'Boopie',
                'species' => 'Cat',
                'breed' => 'Ragdoll',
                'DOB' => '2010-03-26',
                'gender' => 'M',
                'weight' => 8.1,
                'customerId' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'petId' => 37,
                'petName' => 'Cleo',
                'species' => 'Cat',
                'breed' => 'Birman',
                'DOB' => '2000-02-17',
                'gender' => 'M',
                'weight' => 8.8,
                'customerId' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'petId' => 38,
                'petName' => 'Nick',
                'species' => 'Cat',
                'breed' => 'Birman',
                'DOB' => '2009-12-10',
                'gender' => 'M',
                'weight' => 7.7,
                'customerId' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'petId' => 39,
                'petName' => 'Ziggy',
                'species' => 'Dog',
                'breed' => 'Kelpie',
                'DOB' => '2012-05-08',
                'gender' => 'M',
                'weight' => 4.3,
                'customerId' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'petId' => 40,
                'petName' => 'Bazza',
                'species' => 'Dog',
                'breed' => 'Kelpie',
                'DOB' => '2006-10-23',
                'gender' => 'M',
                'weight' => 11.6,
                'customerId' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'petId' => 41,
                'petName' => 'Bindi',
                'species' => 'Dog',
                'breed' => 'Australian Terrier',
                'DOB' => '2007-02-10',
                'gender' => 'M',
                'weight' => 12.9,
                'customerId' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'petId' => 42,
                'petName' => 'Butch',
                'species' => 'Dog',
                'breed' => 'Boxer',
                'DOB' => '2001-01-18',
                'gender' => 'M',
                'weight' => 10.5,
                'customerId' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'petId' => 43,
                'petName' => 'Mitzi',
                'species' => 'Dog',
                'breed' => 'Maltese Terrier',
                'DOB' => '2006-02-28',
                'gender' => 'F',
                'weight' => 18.6,
                'customerId' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'petId' => 44,
                'petName' => 'Rusty',
                'species' => 'Dog',
                'breed' => 'Red Setter',
                'DOB' => '2009-04-01',
                'gender' => 'M',
                'weight' => 11.4,
                'customerId' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'petId' => 45,
                'petName' => 'Pippa',
                'species' => 'Dog',
                'breed' => 'Whippet',
                'DOB' => '2008-04-16',
                'gender' => 'F',
                'weight' => 7.9,
                'customerId' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'petId' => 46,
                'petName' => 'Top',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2011-05-20',
                'gender' => 'F',
                'weight' => 4.0,
                'customerId' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'petId' => 47,
                'petName' => 'Red',
                'species' => 'Dog',
                'breed' => 'King Charles spaniel',
                'DOB' => '2012-09-27',
                'gender' => 'M',
                'weight' => 10.1,
                'customerId' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'petId' => 48,
                'petName' => 'Blue',
                'species' => 'Dog',
                'breed' => 'Maltese Poodle',
                'DOB' => '2001-05-19',
                'gender' => 'M',
                'weight' => 8.9,
                'customerId' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'petId' => 49,
                'petName' => 'Jarrad',
                'species' => 'Dog',
                'breed' => 'Jack Russell',
                'DOB' => '2007-05-23',
                'gender' => 'M',
                'weight' => 17.9,
                'customerId' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'petId' => 50,
                'petName' => 'Amigo',
                'species' => 'Dog',
                'breed' => 'Maltese Poodle',
                'DOB' => '2000-04-25',
                'gender' => 'M',
                'weight' => 15.9,
                'customerId' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'petId' => 51,
                'petName' => 'Bonkers',
                'species' => 'Dog',
                'breed' => 'Dachshund',
                'DOB' => '2012-01-26',
                'gender' => 'M',
                'weight' => 4.0,
                'customerId' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'petId' => 52,
                'petName' => 'Bongo',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2001-11-02',
                'gender' => 'M',
                'weight' => 11.5,
                'customerId' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'petId' => 53,
                'petName' => 'Crazy Horse',
                'species' => 'Dog',
                'breed' => 'Maltese Poodle',
                'DOB' => '2001-03-26',
                'gender' => 'M',
                'weight' => 17.8,
                'customerId' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'petId' => 54,
                'petName' => 'Wooffles',
                'species' => 'Dog',
                'breed' => 'King Charles spaniel',
                'DOB' => '2006-03-21',
                'gender' => 'F',
                'weight' => 3.2,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'petId' => 55,
                'petName' => 'Darling',
                'species' => 'Dog',
                'breed' => 'Afghan Hound',
                'DOB' => '2001-09-27',
                'gender' => 'F',
                'weight' => 9.6,
                'customerId' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'petId' => 56,
                'petName' => 'Precious',
                'species' => 'Dog',
                'breed' => 'Pekinese',
                'DOB' => '2006-05-02',
                'gender' => 'F',
                'weight' => 19.1,
                'customerId' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'petId' => 57,
                'petName' => 'Zog',
                'species' => 'Dog',
                'breed' => 'Border Collie',
                'DOB' => '2012-10-21',
                'gender' => 'F',
                'weight' => 15.5,
                'customerId' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'petId' => 58,
                'petName' => 'Max',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2009-11-03',
                'gender' => 'M',
                'weight' => 11.4,
                'customerId' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'petId' => 59,
                'petName' => 'Dingo',
                'species' => 'Dog',
                'breed' => 'Poodle',
                'DOB' => '2000-06-28',
                'gender' => 'M',
                'weight' => 14.3,
                'customerId' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'petId' => 60,
                'petName' => 'Wolf',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2006-10-21',
                'gender' => 'M',
                'weight' => 16.6,
                'customerId' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'petId' => 61,
                'petName' => 'Slobberchops',
                'species' => 'Dog',
                'breed' => 'Boxer',
                'DOB' => '2009-12-28',
                'gender' => 'M',
                'weight' => 3.4,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'petId' => 62,
                'petName' => 'Thief',
                'species' => 'Dog',
                'breed' => 'Border Collie',
                'DOB' => '2008-10-27',
                'gender' => 'M',
                'weight' => 7.6,
                'customerId' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'petId' => 63,
                'petName' => 'Buttsniffer',
                'species' => 'Dog',
                'breed' => 'Labradoodle',
                'DOB' => '2006-06-04',
                'gender' => 'M',
                'weight' => 11.8,
                'customerId' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'petId' => 64,
                'petName' => 'Ferdy',
                'species' => 'Dog',
                'breed' => 'Maltese Poodle',
                'DOB' => '1998-07-25',
                'gender' => 'M',
                'weight' => 9.0,
                'customerId' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'petId' => 65,
                'petName' => 'Ursula',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2000-06-13',
                'gender' => 'F',
                'weight' => 6.3,
                'customerId' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'petId' => 66,
                'petName' => 'Bella',
                'species' => 'Dog',
                'breed' => 'Pomeranian',
                'DOB' => '2005-08-29',
                'gender' => 'F',
                'weight' => 10.3,
                'customerId' => 64,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'petId' => 67,
                'petName' => 'Gerda',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'DOB' => '2007-07-23',
                'gender' => 'F',
                'weight' => 16.0,
                'customerId' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'petId' => 68,
                'petName' => 'Sammy',
                'species' => 'Dog',
                'breed' => 'Border Collie',
                'DOB' => '2003-08-14',
                'gender' => 'M',
                'weight' => 16.8,
                'customerId' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'petId' => 69,
                'petName' => 'Chuck',
                'species' => 'Dog',
                'breed' => 'King Charles spaniel',
                'DOB' => '2002-12-14',
                'gender' => 'M',
                'weight' => 13.5,
                'customerId' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'petId' => 70,
                'petName' => 'Burglar',
                'species' => 'Ferret',
                'breed' => '',
                'DOB' => '2004-09-30',
                'gender' => 'F',
                'weight' => 11.4,
                'customerId' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'petId' => 71,
                'petName' => 'Mike',
                'species' => 'Ferret',
                'breed' => 'Cinammon Ferret',
                'DOB' => '2012-10-13',
                'gender' => 'M',
                'weight' => 7.8,
                'customerId' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'petId' => 72,
                'petName' => 'Nerdwood',
                'species' => 'Ferret',
                'breed' => 'Cinammon Ferret',
                'DOB' => '2005-02-09',
                'gender' => 'M',
                'weight' => 18.7,
                'customerId' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'petId' => 73,
                'petName' => 'Frederico',
                'species' => 'Ferret',
                'breed' => '',
                'DOB' => '1998-07-13',
                'gender' => 'M',
                'weight' => 4.5,
                'customerId' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'petId' => 74,
                'petName' => 'Felix',
                'species' => 'Ferret',
                'breed' => '',
                'DOB' => '2011-11-08',
                'gender' => 'M',
                'weight' => 18.3,
                'customerId' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'petId' => 75,
                'petName' => 'Trapper',
                'species' => 'Ferret',
                'breed' => '',
                'DOB' => '2011-06-18',
                'gender' => 'F',
                'weight' => 11.2,
                'customerId' => 71,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'petId' => 76,
                'petName' => 'Sneaky Whiskers',
                'species' => 'Ferret',
                'breed' => 'Butterscotch Ferret',
                'DOB' => '2008-08-20',
                'gender' => 'F',
                'weight' => 4.4,
                'customerId' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'petId' => 77,
                'petName' => 'Greg',
                'species' => 'Snake',
                'breed' => 'Eel Snake',
                'DOB' => '2009-10-06',
                'gender' => 'M',
                'weight' => 6.6,
                'customerId' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'petId' => 78,
                'petName' => 'Woodie',
                'species' => 'Snake',
                'breed' => 'Python',
                'DOB' => '2010-01-30',
                'gender' => 'M',
                'weight' => 11.9,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'petId' => 79,
                'petName' => 'Jools',
                'species' => 'Snake',
                'breed' => 'Brown Snake',
                'DOB' => '2007-09-10',
                'gender' => 'F',
                'weight' => 16.3,
                'customerId' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'petId' => 80,
                'petName' => 'Suzie',
                'species' => 'Snake',
                'breed' => 'Black Snake',
                'DOB' => '2011-06-14',
                'gender' => 'F',
                'weight' => 15.7,
                'customerId' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'petId' => 81,
                'petName' => 'Stretch',
                'species' => 'Snake',
                'breed' => 'Python',
                'DOB' => '2010-05-20',
                'gender' => 'F',
                'weight' => 8.9,
                'customerId' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'petId' => 82,
                'petName' => 'Thermal',
                'species' => 'Koala',
                'breed' => '',
                'DOB' => '2009-09-06',
                'gender' => 'M',
                'weight' => 18.2,
                'customerId' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'petId' => 83,
                'petName' => 'Matt',
                'species' => 'Goat',
                'breed' => '',
                'DOB' => '2012-03-01',
                'gender' => 'M',
                'weight' => 16.5,
                'customerId' => 62,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'petId' => 84,
                'petName' => 'Moose',
                'species' => 'Goat',
                'breed' => '',
                'DOB' => '2011-08-25',
                'gender' => 'F',
                'weight' => 13.5,
                'customerId' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'petId' => 85,
                'petName' => 'Garry',
                'species' => 'Goat',
                'breed' => '',
                'DOB' => '2011-01-19',
                'gender' => 'M',
                'weight' => 11.8,
                'customerId' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'petId' => 86,
                'petName' => 'Peter',
                'species' => 'Rabbit ',
                'breed' => '',
                'DOB' => '2008-08-20',
                'gender' => 'M',
                'weight' => 9.1,
                'customerId' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'petId' => 87,
                'petName' => 'Hopper',
                'species' => 'Rabbit ',
                'breed' => '',
                'DOB' => '2012-07-16',
                'gender' => 'F',
                'weight' => 7.8,
                'customerId' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'petId' => 88,
                'petName' => 'Thunder',
                'species' => 'Rabbit ',
                'breed' => 'Angora',
                'DOB' => '2011-01-29',
                'gender' => 'F',
                'weight' => 7.1,
                'customerId' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'petId' => 89,
                'petName' => 'Breedz',
                'species' => 'Rabbit ',
                'breed' => '',
                'DOB' => '2012-09-18',
                'gender' => 'M',
                'weight' => 5.8,
                'customerId' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'petId' => 90,
                'petName' => 'Sunflower',
                'species' => 'Rabbit ',
                'breed' => '',
                'DOB' => '2007-04-10',
                'gender' => 'F',
                'weight' => 3.3,
                'customerId' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'petId' => 91,
                'petName' => 'Mug',
                'species' => 'Rabbit ',
                'breed' => '',
                'DOB' => '2010-12-26',
                'gender' => 'F',
                'weight' => 6.6,
                'customerId' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'petId' => 92,
                'petName' => 'Midnight',
                'species' => 'Mouse',
                'breed' => '',
                'DOB' => '2008-05-21',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'petId' => 93,
                'petName' => 'Hashimoto',
                'species' => 'Mouse',
                'breed' => '',
                'DOB' => '2008-07-27',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'petId' => 94,
                'petName' => 'Claudette',
                'species' => 'Mouse',
                'breed' => '',
                'DOB' => '2008-05-31',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'petId' => 95,
                'petName' => 'Toffee',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2010-05-25',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'petId' => 96,
                'petName' => 'Fudge',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2012-01-06',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'petId' => 97,
                'petName' => 'Caramel',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2012-01-31',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'petId' => 98,
                'petName' => 'Dollar',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2010-03-16',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'petId' => 99,
                'petName' => 'Patches',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2011-09-08',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'petId' => 100,
                'petName' => 'Splodge',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2010-07-09',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'petId' => 101,
                'petName' => 'Nibbles',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2008-06-01',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'petId' => 102,
                'petName' => 'Twitch',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2007-11-22',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'petId' => 103,
                'petName' => 'Chomper',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2008-03-24',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'petId' => 104,
                'petName' => 'Buck',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2012-11-13',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'petId' => 105,
                'petName' => 'Seal',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2011-07-16',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'petId' => 106,
                'petName' => 'Lisa',
                'species' => 'Guinea Pig',
                'breed' => '',
                'DOB' => '2007-04-25',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'petId' => 107,
                'petName' => 'Percy',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2010-06-14',
                'gender' => 'M',
                'weight' => 0.0,
                'customerId' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'petId' => 108,
                'petName' => 'Hannah',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2007-09-04',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'petId' => 109,
                'petName' => 'Lurch',
                'species' => 'Rat',
                'breed' => '',
                'DOB' => '2010-03-09',
                'gender' => 'F',
                'weight' => 0.0,
                'customerId' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'petId' => 110,
                'petName' => 'Teacher',
                'species' => 'Tortoise',
                'breed' => '',
                'DOB' => '2011-03-31',
                'gender' => 'M',
                'weight' => 11.0,
                'customerId' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}